lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    
    # Configuration des extracteurs de token
    token_extractors:
        authorization_header:
            enabled: false  # Désactive l'extraction depuis le header Authorization
        cookie:
            enabled: true   # Active l'extraction depuis un cookie
            name: jwt_token # Nom du cookie à lire