nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: true
    paths:
        '^/':
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
            
        '^/api/token/refresh':
            allow_origin: ['http://localhost:5173']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type']
            allow_credentials: true
